### ISSUE TITLE
config update doesn't change detected version of osquery

### ISSUE THREAD

**Issue by blackfist** [heroku/windmill#28]
When an endpoint checks in for a new config it sends a user-agent that indicates what version of osquery the endpoint is running. Windmill should take that and update the recorded version of osquery.

**Comment by sroberts** [comment]
It could also let you specify that a config requires a certain minimum version of osquery and only provide the right one.

It would  also be nice if Windmill could generate a report of the osquery versions and hosts that need updating.

**Comment by sroberts** [comment]
Man I've said that same thing about half a dozen different configuration issues.
