### ISSUE TITLE
Time Diff

### ISSUE THREAD

**Issue by sroberts** [heroku/windmill#31]
<img width="1163" alt="screen_shot_2015-10-17_at_9_12_05_am" src="https://cloud.githubusercontent.com/assets/44774/10559077/63d5bcbc-74b5-11e5-92b9-7223d88e2de7.png">

It'd be great if the `Last Config Refresh` also displayed time since last refresh, just as a basic `+1h22m` sorta format. Not deathly essential, just would be useful, esp for testing.

**Comment by blackfist** [comment]
I'm going to need something like this too since at some point I'm going to
need a script to reap old machines from the database.

**Comment by sroberts** [comment]
It would still be a calculated field, but I think it could be useful, as well as an API endpoint.

**Comment by sroberts** [comment]
You're an unstoppable issue killing machine.
