### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by sroberts** [heroku/windmill#38]
All actions done by the GUI interface should be programmatically accessible via a REST API. 

This should be pretty simple (if time consuming) based on the current configuration and will make the whole thing easier, clearer, and more maintainable.

**Comment by sroberts** [comment]
Being fixed in #48.

**Comment by blackfist** [comment]
I'm going to close this ticket now because #48 has been merged into master. We don't have full coverage of the GUI now, but I think we should make individual tickets from this point on for making api fixes.

**Comment by sroberts** [comment]
I think the current API covers the core use cases I was concerned with, and I agree it makes the most sense for follow ups to come as their own PRs.
