### ISSUE TITLE
bug: canary does 1 extra node

### ISSUE THREAD

**Issue by lexelby** [heroku/windmill#57]
Steps to reproduce:

1. Get a config group with a goodly number of nodes (mine has 50).
2. Add a new config.
3. Canary it to 3 nodes (not a percentage).

Observed results:

4 nodes get the config.

Expected results:

3 nodes get the config.

**Comment by blackfist** [comment]
WAT?

**Comment by blackfist** [comment]
I expect that with a percentage because of rounding, but the number of nodes should not do that. I will investigate further.

**Comment by lexelby** [comment]
Yeah, I have to admit to being kind of amused by this bug :)
