### ISSUE TITLE
some method to clean old nodes

### ISSUE THREAD

**Issue by lexelby** [heroku/windmill#62]
We have nodes enter and leave our fleet all the time, and this clutters windmill.  Some method to clean or at least hide old nodes in the UI would be useful.  A command we can run with `heroku run` would be a good stopgap.

**Comment by blackfist** [comment]
I think this is basically what we need. Obviously needs some cleanup

```
require_relative 'server'

@stale = Endpoint.where(last_config_time: 1.day.ago..Time.now)
@stale.each do |e|
  e.destroy
end
```

**Comment by lexelby** [comment]
I think you just trolled me.  I believe that kills everything that HAS checked in within the past day.

**Comment by blackfist** [comment]
lol, oops. Sorry about the trolling.

**Comment by lexelby** [comment]
It's okay, I roled back the db. ;)
